#  ./k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tz-lookup
  labels:
    app: tz-lookup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tz-lookup
  template:
    metadata:
      labels:
        app: tz-lookup
    spec:
      containers:
        - name: tz-lookup
          image: ghcr.io/jms/tz_lookup:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
